[package]
edition = "2021"
name = "ntfs-upcase"
version = "0.1.0-dev"

[dependencies]
derive_more = "0.99"
byteorder = "1.4"
lazy_static = { version = "1.4", optional = true }

[features]
default = [ "lazy_static" ]
